### ISSUE TITLE
Default adapter profile in hardware profile is not respected during add-nodes

### ISSUE THREAD

**Issue by cameronbrunner** [UnivaCorporation/tortuga#359]
I have set a default adapter profile on my hardware profile but it was not used as the default when adding a new node.  

```
    add-nodes --count 1 --hardware-profile Monitoring-Reporting --software-profile Monitoring-Reporting

[root@ip-10-0-62-69 cloud]#     add-nodes --count 1 --hardware-profile Monitoring-Reporting --software-profile Monitoring-Reporting
Add host session [465c3cc8-a48f-4c60-94bf-6bec6d03c188] created successfully.
 Use 'get-node-requests -r 465c3cc8-a48f-4c60-94bf-6bec6d03c188' to query request status
[root@ip-10-0-62-69 cloud]# get-hardware-profile --name Monitoring-Reporting
Monitoring-Reporting
  - Description: Copy of aws Nodes
  - Install type: package
  - Name format: *
  - Resource adapter: aws (location: remote, cost: 0)
      - Default configuration profile: Monitoring-Reporting
  - Tags: (none)
```

And from the log...

```
- id: 0dd8ef1e-2b45-4f29-bea5-165e669306ad
  message: None
  name: add-node-request-queued
  request:
    count: 1
    force: false
    hardwareProfile: unisight
    isIdle: false
    resource_adapter_configuration: default
    softwareProfile: unisight
  request_id: 1
  timestamp: '2018-09-10T19:17:06.379778+00:00'
  type: event
- id: 34d9607e-03fe-4ad0-9269-ba0392a8c24d
  message: None
  name: add-node-request-complete
  request:
    addHostSession: 465c3cc8-a48f-4c60-94bf-6bec6d03c188
    count: 1
    force: false
    hardwareProfile: Monitoring-Reporting
    isIdle: false
    resource_adapter_configuration: default
    softwareProfile: Monitoring-Reporting
  request_id: 1
  timestamp: '2018-09-10T21:14:09.926066+00:00'
  type: event
- id: 66b9ea06-7435-4c85-bd95-3d7dd9ba33f7
  message: None
  name: add-node-request-queued
  request:
    count: 1
    force: false
    hardwareProfile: Monitoring-Reporting
    isIdle: false
    resource_adapter_configuration: default
    softwareProfile: Monitoring-Reporting
  request_id: 1
  timestamp: '2018-09-10T21:13:56.410727+00:00'
  type: event
- id: 520d3061-e11a-41e6-89ce-a222dcdb7295
  message: None
  name: node-state-changed
  node:
    addHostSession: 9041891c-ba81-4b8b-83c3-dac8e225b6de
    bootFrom: 0
    destSPId: null
    hardwareProfileId: 3
    hardwareprofile:
      admins: []
      cost: 0
      default_resource_adapter_config: null
      description: Copy of aws Nodes
      id: 3
      idleSoftwareProfileId: null
      initrd: null
      installType: package
      kernel: null
      kernelParams: null
      localBootParams: null
      location: remote
      name: unisight
      nameFormat: '*'
      networks: []
      nics: []
      nodes: []
      softwareOverrideAllowed: false
      tags: null
    id: 2
    instance: null
    isIdle: false
    lastUpdate: null
    lockedState: Unlocked
    name: ip-10-0-10-139.us-east-2.compute.internal
    nics: []
    public_hostname: ec2-18-222-121-167.us-east-2.compute.amazonaws.com
    rack: 0
    rank: 0
    resource_adapter: aws
    softwareProfileId: 3
    softwareprofile:
      admins: []
      components: []
      description: unisight Nodes
      hardwareprofiles: []
      id: 3
      initrd: initrd-centos-7.5-x86_64.img
      isIdle: false
      kernel: kernel-centos-7.5-x86_64
      kernelParams: null
      kitsources: []
      lockedState: Unlocked
      maxNodes: 1
      metadata: null
      minNodes: -1
      name: unisight
      nodes: []
      osId: 1
      partitions: []
      tags: null
      type: compute
    state: Provisioned
    tags: {}
    vcpus: null
  previous_state: Created
  timestamp: '2018-09-10T19:17:19.360599+00:00'
  type: event
```
